# Generated by Django 3.1.3 on 2020-12-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App_name',
            new_name='Task',
        ),
    ]
